name: all-checks

on:
  push:
    branches: [ master ]
  pull_request:

env:
  GO_VERSION: 1.14
  GOTEST: 'gotestsum --'

jobs:

  all-checks:
    name: checks # don't change, this name is used in repository restricts!
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{env.GO_VERSION}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
